export const headCells = [
    {
        id: 'sno',
        numeric: true,
        disablePadding: false,
        label: '#',
    },
    {
        id: 'exercise',
        numeric: false,
        disablePadding: true,
        label: 'Exercise',
    },
    {
        id: 'muscle',
        numeric: false,
        disablePadding: false,
        label: 'Muscle',
    },
    {
        id: 'equipments',
        numeric: false,
        disablePadding: false,
        label: 'Equipments',
    },
    {
        id: 'date_added',
        numeric: false,
        disablePadding: false,
        label: 'Date added',
    },
    {
        id: 'status',
        numeric: false,
        disablePadding: false,
        label: 'Status',
    },
];

export const rows = [
    {
        sno: 1,
        exercise: "cross-fit 30 min body weight only full tone",
        muscle: "triceps",
        equipments: "Dumbbells",
        date_added: "23/12/23",
        status: "active",
    },
    {
        sno: 2,
        exercise: "HIIT cardio blast",
        muscle: "cardio",
        equipments: "None",
        date_added: "24/12/23",
        status: "active",
    },
    {
        sno: 3,
        exercise: "Powerlifting basics",
        muscle: "quadriceps",
        equipments: "Barbell",
        date_added: "25/12/23",
        status: "active",
    },
    {
        sno: 4,
        exercise: "Yoga for flexibility",
        muscle: "flexibility",
        equipments: "Yoga mat",
        date_added: "26/12/23",
        status: "active",
    },
    {
        sno: 5,
        exercise: "Core strength challenge",
        muscle: "core",
        equipments: "Exercise ball",
        date_added: "27/12/23",
        status: "active",
    },
    {
        sno: 6,
        exercise: "Upper body sculpting with resistance bands",
        muscle: "upper body",
        equipments: "Resistance bands",
        date_added: "28/12/23",
        status: "active",
    },
    {
        sno: 7,
        exercise: "Running intervals for stamina",
        muscle: "stamina",
        equipments: "Running shoes",
        date_added: "29/12/23",
        status: "active",
    },
    {
        sno: 8,
        exercise: "Pilates for core stability",
        muscle: "core",
        equipments: "Pilates ball",
        date_added: "30/12/23",
        status: "active",
    },
    {
        sno: 9,
        exercise: "Kettlebell full-body workout",
        muscle: "full body",
        equipments: "Kettlebell",
        date_added: "31/12/23",
        status: "active",
    },
    {
        sno: 10,
        exercise: "Cycling for cardiovascular health",
        muscle: "cardio",
        equipments: "Stationary bike",
        date_added: "01/01/24",
        status: "active",
    },
    {
        sno: 11,
        exercise: "Bodyweight leg routine",
        muscle: "legs",
        equipments: "None",
        date_added: "02/01/24",
        status: "active",
    },
    {
        sno: 12,
        exercise: "Swimming for overall fitness",
        muscle: "full body",
        equipments: "Swimsuit",
        date_added: "03/01/24",
        status: "active",
    },
    {
        sno: 13,
        exercise: "Dance cardio party",
        muscle: "cardio",
        equipments: "None",
        date_added: "04/01/24",
        status: "active",
    },
    {
        sno: 14,
        exercise: "Rowing machine challenge",
        muscle: "back",
        equipments: "Rowing machine",
        date_added: "05/01/24",
        status: "active",
    },
    {
        sno: 15,
        exercise: "Meditation for mental well-being",
        muscle: "mind",
        equipments: "None",
        date_added: "06/01/24",
        status: "active",
    }
]

export const ExerciseData = {
    title: 'Cross-fit 30 min body weight only full tone',
    muscle: ['Triceps', 'Biceps'],
    equipment: 'Dumbbell',
    date_added: '23.03.23',
    last_modified: '23.03.23',
    status: 'active',
    level: 'Beginner',
    type: 'Cross-fit',
    instructions: [
        'Lie face down on a hyperextension bench, tucking your anckles securely under the footpads.',
        '1. Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction.',
        '2. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms.',
        '3. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back.',
        '4. Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.',
        '5. Repeat for the recommended amount of repetitions.'
    ],
    variations: 'This exercise can also be performed without a hyperextension bench, but in this case you will need a spotter. Also, a similar exercise to this one is the good morning and the stiff-legged deadlift.',
    video_link: 'https://www.youtube.com/watch?v',
    exercise_status: 'activated'
}

export const MuscleTypes = ['Biceps', 'Triceps', 'Shoulders', 'Calves', 'ABS']