export const headCells = [
    {
        id: 'sno',
        numeric: true,
        disablePadding: false,
        label: '#',
    },
    {
        id: 'country',
        numeric: false,
        disablePadding: true,
        label: 'Country',
    },
    {
        id: 'state',
        numeric: false,
        disablePadding: false,
        label: 'State',
    },
    {
        id: 'city',
        numeric: false,
        disablePadding: false,
        label: 'City',
    },
    {
        id: 'status',
        numeric: false,
        disablePadding: false,
        label: 'Status',
    },
];

export const rows = [
    {
        sno: 1,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 2,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 3,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 4,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 5,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 6,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 7,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 8,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 9,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 10,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 11,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 12,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 13,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 14,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
    {
        sno: 15,
        country: "India",
        state: "Haryana",
        city: "Gurgaon",
        status: "active",
    },
]
